### ISSUE TITLE
Error running the python -c "import sklearn; sklearn.show_versions()" command

### ISSUE THREAD

**Issue by verbus** [tmwang7324/Medicaid-Analysis#2]
I get the following error:
$ python -c "import sklearn; sklearn.show_versions()"
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3

**Comment by tmwang7324** [comment]
I'll edit it to python3 since I think it works only with python3.  Thank
you for showing me this error.
